image: docker:19.03.8

variables:
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:19.03.8-dind

before_script:
    - docker info

build:
    before_script:
        - apt install docker
    script:
        - ./deploy.sh
    after_script:
        - ls build
