include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/blocks/workflow.yml

qt_wasm_website:
  image: invent-registry.kde.org/sysadmin/ci-images/qt-webassembly-builder:latest
  tags:
    - Linux
  stage: build
  variables:
    LANG: en_US.UTF-8
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git
    - git clone https://invent.kde.org/sysadmin/ci-notary-service.git
  script:
    - /qt-webassembly/entrypoint qmake -o build/ CONFIG+=release
    - /qt-webassembly/entrypoint make -C build/
#    - python3 -u ci-notary-service/publishwebsite.py --config ci-utilities/signing/publishwebsite.ini build/
  artifacts:
    paths:
      - build/
