default:
  image:
    name: madmanfred/qt-webassembly
    entrypoint: ["/bin/bash", "-c"]

build:
    script:
      - mkdir build
      - qmake CONFIG+=release -o build
      - make -C build
      - ls build
