default:
    image:
        name: madmanfred/qt-webassembly
        entrypoint: ["/bin/bash"]

build:
    before_script:
        - echo $PATH
        - ls
    script:
        - qmake CONFIG+=release -o build
        - make -C build
    after_script:
        - ls build
