default:
  image:
    name: madmanfred/qt-webassembly
    entrypoint: ["/bin/bash"]
    before_script:
      - mkdir build
      - qmake CONFIG+=release -o build
      - make -C build
      - ls build
